[features]
seeds = false
skip-lint = false

[programs.localnet]
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
price_oracle = "CzpZdoxJhQjtzG7oLgTHinsPjtMFVzRXEYWy1pn3wQ9Z"
access_control = "7XqCdxDjk9QheBci6JQBzH8x6Y3Ny5TKPpcp8VvfgsYv"  # Replace with actual program ID

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/new_id.json"
endpoint = "http://localhost:9900"

[scripts]
deploy = "anchor deploy"
test = "anchor test"

[test]
startup_wait = 10000
validator_port = 9900

[test.validator]
url = "http://localhost:9900"
rpc_port = 9900
