[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "2JWqmJFU9Sf2rQy8NZG2ST4Tty7QwR4j8K3KnTJm6JAU"
asset_manager = "BqWLtQ2GHCoHoCpqhvyKeXW6Mek1t5eSseTC8CpQoBkU"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "5VwhfjgZEqC5C7hjbyniRTwMhbKGBAM3RVBmDzdy6CEg"
lock_manager = "C1bYYuja1ze1wsJWd1Fo31jWB1nP1miX5Xq25R3mSKmM"
price_oracle = "DEBC37xPGm1wiYqiLCZZy4dquPnukeiYzFASirNdnoJz"
redemption_manager = "93wY4rMgYBcgPfYKiPFX3ib9xp1k3onW2W1aP5FX9JCT"
xxusd_token = "GxjY9UDfh8axqTyXnnBz4jhspkoKAoMzdbrWSG2tg6X6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
