[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "6E1Ng9G1PUUeY6evpb16affGPXuNt1Lgn8ZRvaaqZjGT"
asset_manager = "7Sns8TGLp4miuKSjfegEyyLhwXWthTYpvACWo4LqTX21"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "42Av3ni251qsipXFoVz2UEtHND2L8eekDcJ27U3Nt7j7"
lock_manager = "FuHbrWPearWxCeCSjHjUSA4C3ond2nSPjyctQ6XyCfk4"
price_oracle = "E64rZKSb7ygRteLUXd9AgQw4savQvBzRyHshPMPvvKX7"
redemption_manager = "HtB62J3fEbqu1NwevNkpVpoJjUMGsSG7zLWrH2Tvjrt5"
xxusd_token = "D9KACEqw5Eki2cD7i91n4pVNHmb97ug18yN8E6TavFnF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
