[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "4kjF7HMVZN4S5x3kh9EZ4mUK5WbmpdrZMncv1zzakikd"
asset_manager = "AjBujFb3FUqwK68TwviupnwTTGsdftF1uNGDnepn2n4A"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "DNwntRWby3UTYuDtp7nqPPJp9dwoaF5n9PUxv7Z7a1mB"
lock_manager = "4JcTcdcjoQzuQm2sEMjHC9NmUroHnxz6SKmq9HGvXDiC"
price_oracle = "2UWkTb3Y2zWmjhBbM5r3pv51jBkHr1tK4q4DE8Dnr8sB"
redemption_manager = "4cpZCegz9towsw4UU8E4YmZx4N7D9pC5ocpAYuMEtFLt"
xxusd_token = "D5THoCoahHznfsRUVPNNrQu1ruggy7w78hzh9j3yUXe2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
