[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "Dj76V2fYa7WXc8w2W3dXrb2mFhqHFPVvXuU2Y9oPLguC"
asset_manager = "B4txDkrB5v9YyMzJd5nEfJFUGAu5ygF1G7nVJEEimE94"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "4JEk69GeWgxdyAV1aknhDwCNn3y4HSxvfA1xHv6tkd56"
lock_manager = "3rtwsYug6zVkiy8fv8jZcb6GDPuhQTy55Y1US351HTg9"
price_oracle = "BJgtS7aqPokyfz3vLqPKMv6EgwG9jTrXS6txA3Wkmj1r"
redemption_manager = "FrPckbV5Xf358qJgbeSJKZgMDCHFouaVRZPodLWYM2Sr"
xxusd_token = "3EPheKh3Eg5ynYYa2VHxukcYWsxsG9vxVrDRreirbmnh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
