[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "5G3YjJ8PNAhPeDSZY1kbdPpYG21C8FRMwN1VuSFtR7Qe"
asset_manager = "4SVxH6iDcVbmVhM3LCgqvzgkbe9TwJBhNsswTUhLbWAo"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "HqrUNQ7jUcKg1h2jhrYmKcM5HJY49uEMzV69dD1NYtHU"
lock_manager = "CZ8w1xFR89sNYWg9kLWDVmvoqNTUDLy4A3nTmVpnfFPH"
price_oracle = "H2Fcr4ZNGkNZ6Trj8eqZxtDRoWGSvfChAsjqLB6V7RtX"
redemption_manager = "CUUCkNpfbnstb51aqy6fLAzutDYQPYSUo2v9jfs8ZLL5"
xxusd_token = "2hCNUd8cJPQowav5uZvFMaZrNZU9WXKhmAaqfpSxuq32"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
