[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "CxG6PB8YC9aAjZ7NA3CjyuCY7nUBysiuBdwUtMkJL4H1"
asset_manager = "J2d25fvQuru93AoCKMDQPgR6nunFaksTr16Yxhfo972G"
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
hedging_strategy = "BQygrdv9Vu7Spi2VtjnmNRxUdncZN7AhKnCQRrimxkGQ"
lock_manager = "PsqNwvCbr7zJN4VS7e683QUtaMFzragmHzAxXktdEXm"
price_oracle = "Bwcq4rnU6E3rHi7Zqs5yyymxG5tRhzYS5WxCQN874dpW"
redemption_manager = "FombPC6gW8sJbHYUFPLBrR5bfMwYg7xtKgMHjBJBmDjP"
xxusd_token = "SWVfJhaeUHudiSMdswtpuGnwp6xEoixHwtgtvHUyFft"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_id.json"

[scripts]
deploy = "anchor deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
