[features]
seeds = false
skip-lint = false

[programs.localnet]
flexxcash-poc = "3a3whekXLP4nu9HPdbrtPp6rqe1XG7WwoddhrfQXZYmj"
price_oracle = "CzpZdoxJhQjtzG7oLgTHinsPjtMFVzRXEYWy1pn3wQ9Z"
access_control = "7XqCdxDjk9QheBci6JQBzH8x6Y3Ny5TKPpcp8VvfgsYv"
xxusd_token = "H1G2rsSaNmDovqg1wBmDZq23q9KYAMZdk3pNj4SZwhWS"
asset_manager = "91hM5ZdHVbH7tH1a21QHRmPEFkHWS532DfcpGPBUkdAF"
lock_manager = "AmP3jbYmGguEcmfr6ies1doxrvWQSWaB5Y37pN7Jowu1"
redemption_manager = "BhBNrpuriccL3n6T1QvottBmZ1oHMeuaZus4UXjodxz9"
hedging_strategy = "4QrrLAhjf24ufosccAAUvsw2cVnw5mpiqLwxuZxjgd1i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/new_id.json"
endpoint = "http://localhost:8899"

[scripts]
deploy = "anchor deploy"
test = "anchor test"

[test]
startup_wait = 10000
validator_port = 8899
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "http://localhost:8899"
rpc_port = 8899