[package]
name = "price_oracle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
switchboard-on-demand = "0.1.14"
rust_decimal = "1.26.0"